version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-production
          command: 'npm install --production'
      - run:
          name: build 
          command: 'npm run build'
  test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: 'npm install'
      - run:
          name: test
          command: 'npm run test:cicd'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
